version: "3"
services:
  # react front end client
  react-client:
    stdin_open: true
    image: react-client
    build:
      context: react-client
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./react-client/javascript:/app/javascript
  # gateway to proxy requests to both the client & node gateway
  nginx-gateway:
    restart: always
    depends_on:
      - react-client
    build:
      context: ./nginx-gateway
      dockerfile: Dockerfile
    ports:
      - "3001:80"