FROM node
SHELL ["/bin/bash", "-c"] 
WORKDIR /app

ADD javascript/package.json javascript/package.json 
ADD javascript/tsconfig.json javascript/tsconfig.json 

RUN cd javascript && npm update
RUN cd javascript && NODE_ENV=development npm install

ADD javascript javascript

ENTRYPOINT [ "./start.sh" ]